# Automatically generated by: ros2nix --distro noetic --flake
{
  lib,
  buildRosPackage,
  catkin,
  eigen,
  geometry-msgs,
  message-generation,
  message-runtime,
  nav-msgs,
  roscpp,
  sensor-msgs,
  std-msgs,
  std-srvs,
  tbb_2022_0,
  tf,
}:
buildRosPackage rec {
  pname = "ros-noetic-faster-lio";
  version = "0.0.0";

  src = ./.;

  buildType = "catkin";
  buildInputs = [
    catkin
    message-generation
    tbb_2022_0
  ];
  propagatedBuildInputs = [
    eigen
    geometry-msgs
    message-runtime
    nav-msgs
    roscpp
    sensor-msgs
    std-msgs
    std-srvs
    tf
  ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = "FasterLIO is developed from FastLIO2, see related paper: Chunge Bai et al. Faster-LIO: Lightweight Tightly
        Coupled Lidar-inertial Odometry
        using Parallel Sparse Incremental Voxels, IEEE RA-Letters, 2022";
    license = with lib.licenses; [ bsdOriginal ];
  };
}
