# Automatically generated by: ros2nix --distro noetic --flake
{
  lib,
  buildRosPackage,
  catkin,
  eigen,
  eigen-conversions,
  geometry-msgs,
  glog,
  message-generation,
  message-runtime,
  nav-msgs,
  pcl-ros,
  rosbag,
  roscpp,
  rospy,
  rostest,
  sensor-msgs,
  std-msgs,
  tf,
  yaml-cpp,
}:
buildRosPackage rec {
  pname = "ros-noetic-faster-lio";
  version = "0.0.0";

  src = ./.;

  buildType = "catkin";
  buildInputs = [
    catkin
    message-generation
  ];
  checkInputs = [
    rosbag
    rostest
  ];
  propagatedBuildInputs = [
    eigen
    eigen-conversions
    geometry-msgs
    glog
    message-runtime
    nav-msgs
    pcl-ros
    roscpp
    rospy
    sensor-msgs
    std-msgs
    tf
    yaml-cpp
  ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = "FasterLIO is developed from FastLIO2, see related paper: Chunge Bai et al. Faster-LIO: Lightweight Tightly
        Coupled Lidar-inertial Odometry
        using Parallel Sparse Incremental Voxels, IEEE RA-Letters, 2022";
    license = with lib.licenses; [ bsdOriginal ];
  };
}
